
export const ADD_MARKER = 'ADD_MARKER';
export const ADD_NODE = 'ADD_NODE';

export const UPDATE_MARKER = 'UPDATE_MARKER';
export const UPDATE_NODE = 'UPDATE_NODE';
export const UPDATE_PREVIEW_LINE = 'UPDATE_PREVIEW_LINE';

export const REMOVE_NODE = 'REMOVE_NODE';

export const SET_PREVIEW_LINE = 'SET_PREVIEW_LINE';
export const RESET_PREVIEW_LINE = 'RESET_PREVIEW_LINE';
